## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
addons:
    apt:
        packages:
            - gfortran
python:
  - 0.6
branches:
    only:
        - wavefield_support
notifications:
  email: false
git:
  depth: 99999999
env:
  global:
before_install:
  - mv /home/travis/slimgroup/JUDI.jl /home/travis/slimgroup/JUDI
  - ln -s /home/travis/slimgroup/JUDI /home/travis/.julia/v0.6/
  - sudo apt-get update
  - sudo apt-get install -y gfortran
  - julia -e 'Pkg.clone("https://github.com/slimgroup/SeisIO.jl")'
  - julia -e 'Pkg.clone("https://github.com/slimgroup/JOLI.jl.git")'
  - julia -e 'Pkg.clone("https://github.com/floswald/ApproXD.jl.git")'
   
## uncomment the following lines to override the default test script
script:
    - julia -e 'using JUDI.TimeModeling'

after_success:

