## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
addons:
    apt:
        packages:
            - gfortran
julia:
  - 0.6
  - nightly
branches:
    only:
        - wavefield_support
notifications:
  email: false
git:
  depth: 99999999

before_install:
    - pip install --user git+https://github.com/opesci/devito.git@v3.2.0
    - julia -e 'Pkg.clone("https://github.com/slimgroup/SeisIO.jl.git"); Pkg.build("SeisIO")'
    - julia -e 'Pkg.clone("https://github.com/floswald/ApproXD.jl.git"); Pkg.build("ApproXD")'
    - julia -e 'Pkg.clone("https://github.com/slimgroup/JOLI.jl.git"); Pkg.build("JOLI")'

## uncomment the following lines to override the default test script
script:
    - julia -e 'Pkg.clone(pwd()); Pkg.build("JUDI"); Pkg.resolve()'
    - julia -e 'ENV["PYTHON"]=run(`which python`); Pkg.build("PyCall")'
    - julia -e 'Pkg.test("JUDI"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("JUDI")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("JUDI")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
