## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
branches:
    only:
        - wavefield_support
notifications:
  email: false
git:
  depth: 99999999

before_install:
    - julia -e 'Pkg.clone("git@github.com:slimgroup/SeisIO.jl.git")'
    - julia -e 'Pkg.clone("git@github.com:floswald/ApproXD.jl.git")'
    - julia -e 'Pkg.clone("git@github.com:slimgroup/JOLI.jl.git")'

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
    - julia -e 'Pkg.clone(pwd()); Pkg.build("JUDI"); Pkg.test("JUDI"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("JUDI")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("JUDI")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
